name = "ExamplePackage"
uuid = "317b5d7d-9e68-424e-bdc9-ba6ca06002c3"
authors = ["Federico <red-night@hotmail.it> and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
